version: '2'
services:
    sitemanager-app:
        image: sitemanager
        external_links:
            - sitemanager-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/SiteManager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sitemanager-postgresql:
        extends:
            file: postgresql.yml
            service: sitemanager-postgresql
